export const GET_ALL_ATTRACTIONS_REQUEST = 'GET_ALL_ATTRACTIONS_REQUEST'
export const GET_ALL_ATTRACTIONS_SUCCESS = 'GET_ALL_ATTRACTIONS_SUCCESS'
export const GET_ALL_ATTRACTIONS_FAILURE = 'GET_ALL_ATTRACTIONS_FAILURE'